version: "2"

services:
  zookeeper:
    image: registry.drycc.cc/drycc-addons/zookeeper:canary
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/drycc"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: registry.drycc.cc/drycc-addons/kafka:canary
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/drycc"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
